### ISSUE TITLE
Bitte um Pull des Projekts und Test

### ISSUE THREAD

**Issue by C-Goh** [C-Goh/ModerneSoftwaretechnik2425#8]
Bitte einmal das Projekt pullen und testen, ob alles richtig eingestellt und funktionsfähig ist.

**Comment by C-Goh** [comment]
### Erstellung eines Java Projekts mit Maven

_Apache Maven ist ein in der Programmiersprache Java geschriebenes Kommandozeilenwerkzeug aus der Kategorie der Build-Werkzeuge._

**Notwendige Installationen**
Java (JDK)
Maven

**Verwendete Versionen**
Java: 23.0.1
Maven: 3.9.9

_Falls noch nicht geschehen muss eine JAVA_HOME Variable angelegt werden._
Video zu JAVA_HOME: https://www.youtube.com/watch?v=GSeUjLNiPKs

**Comment by lina1905** [comment]
Konnte das Projekt bauen, bekomme es aber grade nicht hin die Anwendung bei mir lokal auszuführen.
